config/routes.rb
Rails.application.routes.draw do
  resources :rules

  resources :interfaces

end

app/models/interface.rb
class Interface < ActiveRecord::Base
  validates :address, presence: true, ip_address: true
  validates :name, presence: true

  def to_s
    "#{name}(#{address})"
  end
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  belongs_to :src, class_name: "Interface"
  belongs_to :dst, class_name: "Interface"

  validates :src, presence: true
  validates :dst, presence: true
  validates :src_port, presence: true, unless: ->{ src_port_any? }
  validates :dst_port, presence: true, unless: ->{ dst_port_any? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/interfaces_controller.rb
class InterfacesController < ApplicationController
  before_action :set_interface, only: [:show, :edit, :update, :destroy]

  # GET /interfaces
  # GET /interfaces.json
  def index
    @interfaces = Interface.all
  end

  # GET /interfaces/1
  # GET /interfaces/1.json
  def show
  end

  # GET /interfaces/new
  def new
    @interface = Interface.new
  end

  # GET /interfaces/1/edit
  def edit
  end

  # POST /interfaces
  # POST /interfaces.json
  def create
    @interface = Interface.new(interface_params)

    respond_to do |format|
      if @interface.save
        format.html { redirect_to @interface, notice: 'Interface was successfully created.' }
        format.json { render :show, status: :created, location: @interface }
      else
        format.html { render :new }
        format.json { render json: @interface.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interfaces/1
  # PATCH/PUT /interfaces/1.json
  def update
    respond_to do |format|
      if @interface.update(interface_params)
        format.html { redirect_to @interface, notice: 'Interface was successfully updated.' }
        format.json { render :show, status: :ok, location: @interface }
      else
        format.html { render :edit }
        format.json { render json: @interface.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interfaces/1
  # DELETE /interfaces/1.json
  def destroy
    @interface.destroy
    respond_to do |format|
      format.html { redirect_to interfaces_url, notice: 'Interface was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interface
      @interface = Interface.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interface_params
      params.require(:interface).permit(:address, :name)
    end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: [:show, :edit, :update, :destroy]

  # GET /rules
  # GET /rules.json
  def index
    @rules = Rule.all
  end

  # GET /rules/1
  # GET /rules/1.json
  def show
  end

  # GET /rules/new
  def new
    @rule = Rule.new
  end

  # GET /rules/1/edit
  def edit
  end

  # POST /rules
  # POST /rules.json
  def create
    @rule = Rule.new(rule_params)

    respond_to do |format|
      if @rule.save
        format.html { redirect_to @rule, notice: 'Rule was successfully created.' }
        format.json { render :show, status: :created, location: @rule }
      else
        format.html { render :new }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rules/1
  # PATCH/PUT /rules/1.json
  def update
    respond_to do |format|
      if @rule.update(rule_params)
        format.html { redirect_to @rule, notice: 'Rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @rule }
      else
        format.html { render :edit }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @rule.destroy
    respond_to do |format|
      format.html { redirect_to rules_url, notice: 'Rule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rule
      @rule = Rule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rule_params
      params.require(:rule).permit(:src_id, :dst_id, :src_port, :dst_port, :src_port_any, :dst_port_any)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interfaces_helper.rb
module InterfacesHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/interfaces/_form.html.erb
<%= form_for(@interface) do |f| %>
  <% if @interface.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interface.errors.count, "error") %> prohibited this interface from being saved:</h2>

      <ul>
      <% @interface.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interfaces/edit.html.erb
<h1>Editing interface</h1>

<%= render 'form' %>

<%= link_to 'Show', @interface %> |
<%= link_to 'Back', interfaces_path %>

app/views/interfaces/index.html.erb
<h1>Listing interfaces</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interfaces.each do |interface| %>
      <tr>
        <td><%= interface.address %></td>
        <td><%= interface.name %></td>
        <td><%= link_to 'Show', interface %></td>
        <td><%= link_to 'Edit', edit_interface_path(interface) %></td>
        <td><%= link_to 'Destroy', interface, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interface', new_interface_path %>

app/views/interfaces/new.html.erb
<h1>New interface</h1>

<%= render 'form' %>

<%= link_to 'Back', interfaces_path %>

app/views/interfaces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @interface.address %>
</p>

<p>
  <strong>Name:</strong>
  <%= @interface.name %>
</p>

<%= link_to 'Edit', edit_interface_path(@interface) %> |
<%= link_to 'Back', interfaces_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nictables</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rules/_form.html.erb
<%= form_for(@rule) do |f| %>
  <% if @rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% @rule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :src_id %><br>
    <%= f.collection_select :src_id, Interface.all, :id, :to_s %>
  </div>
  <div class="field">
    <%= f.label :dst_id %><br>
    <%= f.collection_select :dst_id, Interface.all, :id, :to_s %>
  </div>
  <div class="field">
    <%= f.label :src_port %><br>
    <%= f.number_field :src_port %>
  </div>
  <div class="field">
    <%= f.label :dst_port %><br>
    <%= f.number_field :dst_port %>
  </div>
  <div class="field">
    <%= f.label :src_port_any %><br>
    <%= f.check_box :src_port_any %>
  </div>
  <div class="field">
    <%= f.label :dst_port_any %><br>
    <%= f.check_box :dst_port_any %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rules/edit.html.erb
<h1>Editing rule</h1>

<%= render 'form' %>

<%= link_to 'Show', @rule %> |
<%= link_to 'Back', rules_path %>

app/views/rules/index.html.erb
<h1>Listing rules</h1>

<table>
  <thead>
    <tr>
      <th>Src</th>
      <th>Dst</th>
      <th>Src port</th>
      <th>Dst port</th>
      <th>Src port any</th>
      <th>Dst port any</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rules.each do |rule| %>
      <tr>
        <td><%= rule.src %></td>
        <td><%= rule.dst %></td>
        <td><%= rule.src_port %></td>
        <td><%= rule.dst_port %></td>
        <td><%= rule.src_port_any %></td>
        <td><%= rule.dst_port_any %></td>
        <td><%= link_to 'Show', rule %></td>
        <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
        <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rule', new_rule_path %>

app/views/rules/new.html.erb
<h1>New rule</h1>

<%= render 'form' %>

<%= link_to 'Back', rules_path %>

app/views/rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Src:</strong>
  <%= @rule.src %>
</p>

<p>
  <strong>Dst:</strong>
  <%= @rule.dst %>
</p>

<p>
  <strong>Src port:</strong>
  <%= @rule.src_port %>
</p>

<p>
  <strong>Dst port:</strong>
  <%= @rule.dst_port %>
</p>

<p>
  <strong>Src port any:</strong>
  <%= @rule.src_port_any %>
</p>

<p>
  <strong>Dst port any:</strong>
  <%= @rule.dst_port_any %>
</p>

<%= link_to 'Edit', edit_rule_path(@rule) %> |
<%= link_to 'Back', rules_path %>